// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmVGE2ujRX-qIrqg7BuRhIgNO7hztE4C0',
    appId: '1:494464682902:web:52436d993b4d4bb96e2bb7',
    messagingSenderId: '494464682902',
    projectId: 'vibely-6f2fd',
    authDomain: 'vibely-6f2fd.firebaseapp.com',
    storageBucket: 'vibely-6f2fd.firebasestorage.app',
    measurementId: 'G-ZKEPMPM4QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFV6_EQB64_Nt4HNuhD9Dco92ruZ_wtkQ',
    appId: '1:494464682902:android:3c8873852f6dc9df6e2bb7',
    messagingSenderId: '494464682902',
    projectId: 'vibely-6f2fd',
    storageBucket: 'vibely-6f2fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjouo8e5jZAttNXLGpeD4PaTojj6kHlmw',
    appId: '1:494464682902:ios:7c60edf97e6a4d836e2bb7',
    messagingSenderId: '494464682902',
    projectId: 'vibely-6f2fd',
    storageBucket: 'vibely-6f2fd.firebasestorage.app',
    iosBundleId: 'com.example.vibely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjouo8e5jZAttNXLGpeD4PaTojj6kHlmw',
    appId: '1:494464682902:ios:7c60edf97e6a4d836e2bb7',
    messagingSenderId: '494464682902',
    projectId: 'vibely-6f2fd',
    storageBucket: 'vibely-6f2fd.firebasestorage.app',
    iosBundleId: 'com.example.vibely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmVGE2ujRX-qIrqg7BuRhIgNO7hztE4C0',
    appId: '1:494464682902:web:f3ac3e4849ed8a486e2bb7',
    messagingSenderId: '494464682902',
    projectId: 'vibely-6f2fd',
    authDomain: 'vibely-6f2fd.firebaseapp.com',
    storageBucket: 'vibely-6f2fd.firebasestorage.app',
    measurementId: 'G-5V48RLGH9D',
  );

}